### ISSUE TITLE
autostart

### ISSUE THREAD

**Issue by krtschmr** [BMische/eth.sh#2]
is autostart missing in case power got lost?

**Comment by luigi311** [comment]
The script is only for setup not for automating the start up of the ethminer. The script will install everything you need to start mining with ethminer, you still have to create your start.sh and have that setup to autostart. The script can then be used to overclock your 1060/1070. You can create a script that will run this script with the -o flag so it overclocks and then runs your start.sh and have that start on startup using ubuntu startup application.

**Comment by InDebtBigTime** [comment]
I think this would be easy to incorporate into the main script. I will look into it

**Comment by luigi311** [comment]
Yeah it should be really easy since ethminer is installed globally so you just need to put 2 inputs, 1st for pool and 2nd for wallet address.

**Comment by BMische** [comment]
Done. Marking as closed
