### ISSUE TITLE
where's the miner build?

### ISSUE THREAD

**Issue by iMarlboro** [BMische/eth.sh#4]
where's the miner build?

**Comment by luigi311** [comment]
After you run the script the miner gets built into "/setupethminer/bin/ethminer" the executable is then copied to "/usr/local/sbin/" and you can call it from anywhere by using ethminer from the terminal.

_Sent from my Lge LGLS991 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by iMarlboro** [comment]
I C,thanks.
